[package]
name = "client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
winapi = { version = "0.3", features = [
    "winnt",
    "processthreadsapi",
    "memoryapi",
    "handleapi",
    "synchapi",
    "errhandlingapi",
    "libloaderapi",
    "winuser",
    "basetsd"
] }
lazy_static = "1.4.0"
webview2 = { version = "0.1.4" }
windows = { version = "0.52", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation"] }
