[package]
name = "rebornmp"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "rebornmp"

[dependencies]
winapi = { version = "0.3", features = ["libloaderapi", "winuser", "winnt"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"  # ← добавляем