[package]
name = "client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
winapi = { version = "0.3", features = [
    "winnt",
    "processthreadsapi",
    "memoryapi",
    "handleapi",
    "synchapi",
    "errhandlingapi",
    "libloaderapi",
    "winuser",
    "d3d11",
    "dxgi",
    "d3dcommon"
] }
lazy_static = "1.4.0"
