[package]
name = "launcher"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "launcher"
path = "src/main.rs"

[dependencies]
winapi = { version = "0.3", features = [
    "tlhelp32", "processthreadsapi", "memoryapi", 
    "handleapi", "errhandlingapi", "synchapi", 
    "libloaderapi", "winnt", "minwindef"
] }