[package]
name = "launcher"
version = "0.2.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = [
    "processenv",
    "processthreadsapi",
    "memoryapi",
    "handleapi",
    "synchapi",
    "libloaderapi",
    "winbase",
    "winnt",
    "minwindef",
    "errhandlingapi",
    "securitybaseapi",
    "winerror",
    "fileapi"
] }
chrono = "0.4"
winreg = "0.50"  # Для поиска GTA V в реестре
